USE [QL_QUANCAFE]
GO
CREATE PROCEDURE sp_load_account
AS
BEGIN
	SELECT USERNAME AS N'Tài khoản',DISPLAYNAME AS N'Tên hiển thị', PASSWORD AS N'Mật khẩu', TYPEACCOUNT AS N'Loại tài khoản' FROM ACCOUNT
END
GO

CREATE PROCEDURE sp_load_tableF
AS
BEGIN
	SELECT NAME as N'Tên bàn', STT as N'Trạng thái', TOTAL as N'Tổng tiền' FROM TABLEF
END
GO

CREATE PROCEDURE sp_load_billinfo
@NAMETABLE nvarchar(100)
AS
BEGIN
	SELECT * FROM BILL WHERE NAMETABLE = @NAMETABLE
END
GO

CREATE PROCEDURE sp_load_category
AS
BEGIN
	SELECT NAME as N'Tên danh mục' FROM CATEGORY
END
GO

CREATE PROCEDURE sp_load_food 
@NAMECATEGORY nvarchar(100)
AS
BEGIN
	SELECT NAME as N'Tên món', NAMECATEGORY as N'Tên DM', PRICE as N'Giá'  FROM FOOD WHERE NAMECATEGORY = @NAMECATEGORY
END
GO
CREATE PROCEDURE sp_load_AllFood 
AS
BEGIN
	SELECT NAME as N'Tên món', NAMECATEGORY as N'Tên DM', PRICE as N'Giá'  FROM FOOD
END
GO

CREATE PROCEDURE sp_datban
@NAMETable nvarchar(100)
,@STT nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = @STT WHERE NAME = @NAMETable
END
GO

CREATE PROCEDURE sp_Add_Account
@USERNAME nvarchar(100)
,@DISPLAYNAME nvarchar(100)
,@PASSWORD nvarchar(100)
,@TYPEACCOUNT nvarchar(100)
AS
BEGIN
	INSERT INTO ACCOUNT (USERNAME,DISPLAYNAME,PASSWORD,TYPEACCOUNT) VALUES (@USERNAME,@DISPLAYNAME,@PASSWORD,@TYPEACCOUNT)
END
GO
CREATE PROCEDURE sp_Del_Account
@USERNAME nvarchar(100)
AS
BEGIN
	DELETE FROM ACCOUNT WHERE USERNAME LIKE @USERNAME
END
GO
CREATE PROCEDURE sp_Update_Account
@USERNAME nvarchar(100)
,@DISPLAYNAME nvarchar(100)
,@PASSWORD nvarchar(100)
,@TYPEACCOUNT nvarchar(100)
,@Where_USERNAME nvarchar(100)
AS
BEGIN
	UPDATE ACCOUNT SET USERNAME = @USERNAME, DISPLAYNAME = @DISPLAYNAME,PASSWORD =@PASSWORD,TYPEACCOUNT = @TYPEACCOUNT WHERE USERNAME =@Where_USERNAME
END
GO

CREATE PROCEDURE sp_add_food
@NAMECATEGORY nvarchar(100)
,@NAME nvarchar(100)
,@PRICE float
AS
BEGIN
	INSERT INTO FOOD (NAMECATEGORY, NAME, PRICE) VALUES (@NAMECATEGORY,@NAME,@PRICE)
END
GO
CREATE PROCEDURE sp_del_food
@NAMECATEGORY nvarchar(100)
AS
BEGIN
	DELETE FROM FOOD WHERE NAME LIKE @NAMECATEGORY
END
GO
CREATE PROCEDURE sp_update_food
@NAMECATEGORY nvarchar(100)
,@NAME nvarchar(100)
,@PRICE float
,@Where_name nvarchar(100)
AS
BEGIN
	UPDATE FOOD SET NAME = @NAME, NAMECATEGORY = @NAMECATEGORY, PRICE = @PRICE WHERE NAME =@Where_name
END
GO

CREATE PROCEDURE sp_add_table
@NAME nvarchar(100)
AS
BEGIN
	INSERT INTO TABLEF(NAME,STT,TOTAL) VALUES (@NAME,N'OFFLINE',0)
END
GO
CREATE PROCEDURE sp_del_table
@NAME nvarchar(100)
AS
BEGIN
	DELETE FROM TABLEF WHERE NAME = @NAME
END
GO
CREATE PROCEDURE sp_update_table
@NAME nvarchar(100)
,@Where_NAME nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET NAME = @NAME WHERE NAME = @Where_NAME
END
GO

--Doi mon
CREATE PROCEDURE sp_table_food_bill
@NAME nvarchar(100)
AS
BEGIN
	SELECT BILL.NAMEFOOD, BILL.COUNTS, FOOD.PRICE, TABLEF.TOTAL FROM TABLEF JOIN BILL ON TABLEF.NAME = BILL.NAMETABLE JOIN FOOD ON BILL.NAMEFOOD = FOOD.NAME WHERE TABLEF.NAME like @NAME
END
GO
CREATE PROCEDURE sp_sua_sl_mon
@NAMEF nvarchar(100)
,@NAMET nvarchar(100)
,@count int
AS
BEGIN
	UPDATE BILL SET COUNTS = @count WHERE NAMETABLE like @NAMET AND NAMEFOOD like @NAMEF
END
GO
CREATE PROCEDURE sp_sua_total
@NAMET nvarchar(100)
,@total float
AS
BEGIN
	UPDATE TABLEF SET TOTAL = @total WHERE NAME like @NAMET
END
GO


CREATE PROCEDURE sp_move_food
@NAMETABLE nvarchar(100)
,@NAMEFOOD nvarchar(100)
,@COUNTS int
AS
BEGIN
	INSERT INTO BILL(NAMETABLE,NAMEFOOD,COUNTS) VALUES (@NAMETABLE,@NAMEFOOD,@COUNTS)
END
GO

CREATE PROCEDURE sp_move_table
@TOTAL float
,@NAMET nvarchar(100)
,@NAMEF nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = N'ONLINE', TOTAL = @TOTAL WHERE NAME like @NAMET;
	UPDATE TABLEF SET STT = N'OFFLINE', TOTAL = 0 WHERE NAME like @NAMEF ;
	DELETE FROM BILL WHERE NAMETABLE like @NAMEF ;
END
GO
CREATE PROCEDURE sp_check_table
@NAMET nvarchar(100)
AS
BEGIN
	SELECT BILL.NAMEFOOD, BILL.COUNTS, TABLEF.TOTAL FROM TABLEF JOIN BILL ON TABLEF.NAME = BILL.NAMETABLE WHERE TABLEF.NAME like @NAMET 
END
GO

CREATE PROCEDURE sp_add_category
@NAMEC nvarchar(100)
AS
BEGIN
	INSERT INTO CATEGORY(NAME) VALUES (@NAMEC);
END
GO
CREATE PROCEDURE sp_Del_category
@NAMEC nvarchar(100)
AS
BEGIN
	DELETE FROM CATEGORY WHERE NAME like @NAMEC
END
GO
CREATE PROCEDURE sp_Update_category
@NAMEC nvarchar(100)
,@Where_cate nvarchar(100)
AS
BEGIN
	UPDATE CATEGORY SET NAME = @NAMEC WHERE NAME like @Where_cate
END
GO


CREATE PROCEDURE sp_load_food_table
@NAMET nvarchar(100)
AS
BEGIN
	SELECT BILL.NAMEFOOD, BILL.COUNTS, TABLEF.TOTAL FROM TABLEF JOIN BILL ON TABLEF.NAME = BILL.NAMETABLE WHERE TABLEF.NAME like @NAMET;
END
GO

CREATE PROCEDURE sp_gop_Table
@NAMETABLEA nvarchar(100)
,@NAMETABLEB nvarchar(100)
,@addTotal float
AS
BEGIN
	UPDATE TABLEF SET STT = N'OFFLINE', TOTAL = 0 WHERE NAME like @NAMETABLEA;
	DELETE FROM BILL WHERE NAMETABLE like @NAMETABLEA;
	UPDATE TABLEF SET STT = N'ONLINE', TOTAL += @addTotal WHERE NAME like @NAMETABLEB;
END
GO


CREATE PROCEDURE sp_load_table_where
@NAME nvarchar(100)
AS
BEGIN
	SELECT * FROM TABLEF WHERE NAME like @NAME
END
GO
CREATE PROCEDURE sp_load_bill_where
@NAME nvarchar(100)
AS
BEGIN
	SELECT * FROM BILL WHERE NAMETABLE like @NAME
END
GO
CREATE PROCEDURE sp_clear_table
@NAME nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = N'OFFLINE', TOTAL = 0 WHERE NAME like @NAME
END
GO
CREATE PROCEDURE sp_clear_bill
@NAME nvarchar(100)
AS
BEGIN
	DELETE FROM BILL WHERE NAMETABLE = @NAME
END
GO
CREATE PROCEDURE sp_reset_table
@NAME nvarchar(100)
AS
BEGIN
	UPDATE TABLEF SET STT = N'ONLINE' WHERE NAME like @NAME
END
GO
CREATE PROCEDURE sp_them_mon
@NAME nvarchar(100)
,@NAMEFood nvarchar(100)
,@count int
AS
BEGIN
	INSERT INTO BILL(NAMETABLE,NAMEFOOD,COUNTS) VALUES (@NAME, @NAMEFood, @count);
END
GO
CREATE PROCEDURE sp_tang_slmon
@NAME nvarchar(100)
,@NAMEFood nvarchar(100)
,@count int
AS
BEGIN
	UPDATE BILL SET COUNTS += @count WHERE NAMETABLE like @NAME AND NAMEFOOD like @NAMEFood;
END
GO
CREATE PROCEDURE sp_check_food_table
@NAME nvarchar(100)
,@NAMEFood nvarchar(100)
AS
BEGIN
	SELECT * FROM BILL WHERE NAMETABLE like @NAME AND NAMEFOOD like @NAMEFood
END
GO
CREATE PROCEDURE sp_get_price
@NAMEFood nvarchar(100)
AS
BEGIN
	SELECT PRICE FROM FOOD WHERE NAME like @NAMEFood
END
GO
CREATE PROCEDURE sp_set_total
@NAME nvarchar(100)
,@total float
AS
BEGIN
	UPDATE TABLEF SET TOTAL += @total WHERE NAME like @NAME
END
GO


CREATE PROCEDURE sp_reset_account
@NAME nvarchar(100)
,@PASS nvarchar(100)
, @DISPLAYNAME nvarchar(100)
AS
BEGIN
	UPDATE ACCOUNT SET DISPLAYNAME = @DISPLAYNAME, PASSWORD = @PASS WHERE USERNAME = @NAME;
END
GO
CREATE PROCEDURE sp_addlistbill
	@ID int,
	@NAMETABLE nvarchar(100),
	@TIMECHECKOUT time,
	@DATECHECKOUT date,
	@COUNTS int
AS
BEGIN
	INSERT INTO BILLINFO(ID,NAMETABLE,TIMECHECKOUT,DATECHECKOUT,COUNTS) VALUES(@ID,@NAMETABLE,@TIMECHECKOUT,@DATECHECKOUT,@COUNTS);
END
GO

CREATE PROCEDURE sp_loadlistbill
AS
BEGIN
	SELECT ID AS 'Mã hóa đơn',DATECHECKOUT AS'Ngày xuất HĐ',TIMECHECKOUT AS 'Thời gian', NAMETABLE AS 'Tên bàn',COUNTS AS 'Tổng tiền'FROM BILLINFO
END
GO


CREATE PROCEDURE sp_update_idbill
@IDBILLINFO int
AS
BEGIN
	UPDATE IDBILL SET IDBILLINFO = @IDBILLINFO+1 WHERE IDBILLINFO = @IDBILLINFO
END
GO

CREATE PROCEDURE sp_load_idbill
AS
BEGIN
	SELECT * FROM IDBILL 
END
GO

CREATE PROCEDURE sp_load_customer
AS
BEGIN
	SELECT IDCUSTOMER AS 'Mã Khách Hàng',NAMECUSTOMER AS 'Tên Khách Hàng',NUMBER AS 'Số Điện Thoại',ADDRESS AS'Địa Chỉ' FROM CUSTOMER 
END
GO

CREATE PROCEDURE sp_load_staff
AS
BEGIN
	SELECT IDSTAFF AS 'Mã Nhân Viên',NAMESTAFF AS 'Tên Nhân Viên',NUMBER AS 'Số Điện Thoại',ADDRESS AS'Địa Chỉ',SHIFTTYPE AS 'Thời gian làm việc' FROM STAFF
END
GO

CREATE PROCEDURE sp_load_shifttype
AS
BEGIN
	SELECT SHIFTTYPE FROM SHIFT
END
GO

CREATE PROCEDURE sp_add_customer
    @IDCUSTOMER int,
    @NAMECUSTOMER nvarchar(100),
    @NUMBER nvarchar (10),
    @ADDRESS nvarchar(1000)
AS
BEGIN
	INSERT INTO CUSTOMER(IDCUSTOMER,NAMECUSTOMER,NUMBER,ADDRESS) VALUES (@IDCUSTOMER,@NAMECUSTOMER,@NUMBER,@ADDRESS)
END
GO

CREATE PROCEDURE sp_add_staff
    @IDSTAFF int,
    @NAMESTAFF nvarchar(100),
    @NUMBER nvarchar (10),
    @ADDRESS nvarchar(1000),
	@SHIFTTYPE nvarchar(100)
AS
BEGIN
	INSERT INTO STAFF(IDSTAFF,NAMESTAFF,NUMBER,ADDRESS,SHIFTTYPE) VALUES (@IDSTAFF,@NAMESTAFF,@NUMBER,@ADDRESS,@SHIFTTYPE)
END
GO

CREATE PROCEDURE sp_update_staff
    @IDSTAFF int,
    @NAMESTAFF nvarchar(100),
    @NUMBER nvarchar (10),
    @ADDRESS nvarchar(1000),
	@SHIFTTYPE nvarchar(100)
AS
BEGIN
	UPDATE STAFF SET IDSTAFF = @IDSTAFF, NAMESTAFF = @NAMESTAFF, NUMBER = @NUMBER,ADDRESS=@ADDRESS,SHIFTTYPE=@SHIFTTYPE WHERE IDSTAFF=@IDSTAFF
END
GO

CREATE PROCEDURE sp_update_customer
    @IDCUSTOMER int,
    @NAMECUSTOMER nvarchar(100),
    @NUMBER nvarchar (10),
    @ADDRESS nvarchar(1000)
AS
BEGIN
	UPDATE CUSTOMER SET IDCUSTOMER = @IDCUSTOMER, NAMECUSTOMER = @NAMECUSTOMER, NUMBER = @NUMBER,ADDRESS=@ADDRESS WHERE IDCUSTOMER=@IDCUSTOMER
END
GO

CREATE PROCEDURE sp_Del_staff
@IDSTAFF int
AS
BEGIN
	DELETE FROM STAFF WHERE IDSTAFF= @IDSTAFF
END
GO

CREATE PROCEDURE sp_Del_customer
@IDCUSTOMER int
AS
BEGIN
	DELETE FROM CUSTOMER WHERE IDCUSTOMER= @IDCUSTOMER
END
GO




